/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nathan_kaleb_monica;

/**
 *
 * @author khimes
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popularLabel = new javax.swing.JLabel();
        recentLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchTextArea = new javax.swing.JTextField();
        searchBut = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        popularScroll = new javax.swing.JScrollPane();
        popularTextArea = new javax.swing.JTextArea();
        resultScroll = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        recentScroll = new javax.swing.JScrollPane();
        recentTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        popularLabel.setText("Popular");

        recentLabel.setText("Recently Searched");

        resultLabel.setText("Results:");

        searchPanel.setMaximumSize(new java.awt.Dimension(500, 210));
        searchPanel.setMinimumSize(new java.awt.Dimension(500, 210));
        searchPanel.setPreferredSize(new java.awt.Dimension(500, 210));

        searchTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextAreaActionPerformed(evt);
            }
        });
        searchTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextAreaKeyPressed(evt);
            }
        });

        searchBut.setText("Search");
        searchBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(searchTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBut)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBut))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        displayPanel.setMaximumSize(new java.awt.Dimension(500, 298));
        displayPanel.setMinimumSize(new java.awt.Dimension(500, 298));
        displayPanel.setPreferredSize(new java.awt.Dimension(500, 298));

        popularTextArea.setColumns(20);
        popularTextArea.setRows(5);
        popularTextArea.setFocusable(false);
        popularScroll.setViewportView(popularTextArea);

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        resultTextArea.setFocusable(false);
        resultScroll.setViewportView(resultTextArea);

        recentTextArea.setColumns(20);
        recentTextArea.setRows(5);
        recentTextArea.setFocusable(false);
        recentScroll.setViewportView(recentTextArea);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(popularScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(recentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(resultScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popularScroll)
            .addComponent(resultScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addComponent(recentScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(popularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recentLabel)
                .addGap(33, 33, 33)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularLabel)
                    .addComponent(recentLabel)
                    .addComponent(resultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextAreaActionPerformed

    private void searchButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButMouseClicked

    private void searchTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextAreaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextAreaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel popularLabel;
    private javax.swing.JScrollPane popularScroll;
    private javax.swing.JTextArea popularTextArea;
    private javax.swing.JLabel recentLabel;
    private javax.swing.JScrollPane recentScroll;
    private javax.swing.JTextArea recentTextArea;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JScrollPane resultScroll;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton searchBut;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextArea;
    // End of variables declaration//GEN-END:variables
}
