/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ordermenu;

/**
 *
 * @author Kaleb
 */
public class Kitchen extends javax.swing.JFrame {

    /**
     * Creates new form Kitchen
     */
    public Kitchen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. Thanks -Kaleb
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="This code is wrapped and controls the layout edit cautiously">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        whichtable = new javax.swing.JLabel();
        tablelbl = new javax.swing.JLabel();
        whichsection = new javax.swing.JLabel();
        sectionlbl = new javax.swing.JLabel();
        drinkslbl = new javax.swing.JLabel();
        applbl = new javax.swing.JLabel();
        entreelbl = new javax.swing.JLabel();
        dessertlbl = new javax.swing.JLabel();
        coffeelbl = new javax.swing.JLabel();
        decaflbl = new javax.swing.JLabel();
        hottealbl = new javax.swing.JLabel();
        coldtealbl = new javax.swing.JLabel();
        peachlbl = new javax.swing.JLabel();
        lemonlbl = new javax.swing.JLabel();
        mintlbl = new javax.swing.JLabel();
        pmaxlbl = new javax.swing.JLabel();
        ponelbl = new javax.swing.JLabel();
        rblbl = new javax.swing.JLabel();
        dplbl = new javax.swing.JLabel();
        mdlbl = new javax.swing.JLabel();
        sierralbl = new javax.swing.JLabel();
        pepsilbl = new javax.swing.JLabel();
        coffeenumlbl = new javax.swing.JLabel();
        decafnumlbl = new javax.swing.JLabel();
        hotteanumlbl = new javax.swing.JLabel();
        coldteanumlbl = new javax.swing.JLabel();
        peachnumlbl = new javax.swing.JLabel();
        lemonnumlbl = new javax.swing.JLabel();
        mintnumlbl = new javax.swing.JLabel();
        cwslbl = new javax.swing.JLabel();
        samplelbl = new javax.swing.JLabel();
        fflbl = new javax.swing.JLabel();
        extslbl = new javax.swing.JLabel();
        extsclbl = new javax.swing.JLabel();
        bufflbl = new javax.swing.JLabel();
        sautmushlbl = new javax.swing.JLabel();
        extrlbl = new javax.swing.JLabel();
        nacholbl = new javax.swing.JLabel();
        sbarlbl = new javax.swing.JLabel();
        daysouplbl = new javax.swing.JLabel();
        caesarlbl = new javax.swing.JLabel();
        bsouplbl = new javax.swing.JLabel();
        tbonelbl = new javax.swing.JLabel();
        houselbl = new javax.swing.JLabel();
        classlbl = new javax.swing.JLabel();
        frenchlbl = new javax.swing.JLabel();
        clamlbl = new javax.swing.JLabel();
        hfslbl = new javax.swing.JLabel();
        vanlbl = new javax.swing.JLabel();
        chscakelbl = new javax.swing.JLabel();
        banslbl = new javax.swing.JLabel();
        rbflbl = new javax.swing.JLabel();
        ciclbl = new javax.swing.JLabel();
        ponenumlbl = new javax.swing.JLabel();
        rbnumlbl = new javax.swing.JLabel();
        pmaxnumlbl = new javax.swing.JLabel();
        mdnumlbl = new javax.swing.JLabel();
        sierranumlbl = new javax.swing.JLabel();
        dpnumlbl = new javax.swing.JLabel();
        pepsinumlbl = new javax.swing.JLabel();
        tbonenumlbl = new javax.swing.JLabel();
        frenchnumlbl = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        classnumlbl = new javax.swing.JLabel();
        caesarnumlbl = new javax.swing.JLabel();
        sbarnumlbl = new javax.swing.JLabel();
        bsoupnumlbl = new javax.swing.JLabel();
        daysoupnumlbl = new javax.swing.JLabel();
        clamnumlbl = new javax.swing.JLabel();
        chscakenumlbl = new javax.swing.JLabel();
        hfsnumlbl = new javax.swing.JLabel();
        vannumlbl = new javax.swing.JLabel();
        cicnumlbl = new javax.swing.JLabel();
        bansnumlbl = new javax.swing.JLabel();
        rbfnumlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        request1lbl = new javax.swing.JTextArea();
        customerrequestlbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        request2lbl = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Order ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 36))); // NOI18N

        whichtable.setText("This Order is from Table:");

        tablelbl.setText("_____");

        whichsection.setText("In Section:");

        sectionlbl.setText("_____");

        drinkslbl.setText("The Customer would like the following drinks:");

        applbl.setText("The Customer would like the following Appetizers:");

        entreelbl.setText("The Customer would like the following Entreès:");

        dessertlbl.setText("The Customer would like the following Dessert's:");

        coffeelbl.setText("--------------------");

        decaflbl.setText("--------------------");

        hottealbl.setText("--------------------");

        coldtealbl.setText("--------------------");

        peachlbl.setText("--------------------");

        lemonlbl.setText("--------------------");

        mintlbl.setText("--------------------");

        pmaxlbl.setText("--------------------");

        ponelbl.setText("--------------------");

        rblbl.setText("--------------------");

        dplbl.setText("--------------------");

        mdlbl.setText("--------------------");

        sierralbl.setText("--------------------");

        pepsilbl.setText("--------------------");

        coffeenumlbl.setText("---");

        decafnumlbl.setText("---");

        hotteanumlbl.setText("---");

        coldteanumlbl.setText("---");

        peachnumlbl.setText("---");

        lemonnumlbl.setText("---");

        mintnumlbl.setText("---");

        cwslbl.setText("--------------------");

        samplelbl.setText("--------------------");

        fflbl.setText("--------------------");

        extslbl.setText("--------------------");

        extsclbl.setText("--------------------");

        bufflbl.setText("--------------------");

        sautmushlbl.setText("--------------------");

        extrlbl.setText("--------------------");

        nacholbl.setText("--------------------");

        sbarlbl.setText("--------------------");

        daysouplbl.setText("--------------------");

        caesarlbl.setText("--------------------");

        bsouplbl.setText("--------------------");

        tbonelbl.setText("--------------------");

        houselbl.setText("--------------------");

        classlbl.setText("--------------------");

        frenchlbl.setText("--------------------");

        clamlbl.setText("--------------------");

        hfslbl.setText("-----------------------");

        vanlbl.setText("-----------------------");

        chscakelbl.setText("-----------------------");

        banslbl.setText("---------------------------");

        rbflbl.setText("---------------------------");

        ciclbl.setText("---------------------------");

        ponenumlbl.setText("---");

        rbnumlbl.setText("---");

        pmaxnumlbl.setText("---");

        mdnumlbl.setText("---");

        sierranumlbl.setText("---");

        dpnumlbl.setText("---");

        pepsinumlbl.setText("---");

        tbonenumlbl.setText("---");

        frenchnumlbl.setText("---");

        jLabel80.setText("---");

        classnumlbl.setText("---");

        caesarnumlbl.setText("---");

        sbarnumlbl.setText("---");

        bsoupnumlbl.setText("---");

        daysoupnumlbl.setText("---");

        clamnumlbl.setText("---");

        chscakenumlbl.setText("---");

        hfsnumlbl.setText("---");

        vannumlbl.setText("---");

        cicnumlbl.setText("---");

        bansnumlbl.setText("---");

        rbfnumlbl.setText("---");

        request1lbl.setColumns(20);
        request1lbl.setRows(5);
        jScrollPane2.setViewportView(request1lbl);

        customerrequestlbl.setText("The customer has these appetizer requests:");

        request2lbl.setColumns(20);
        request2lbl.setRows(5);
        jScrollPane3.setViewportView(request2lbl);

        jLabel1.setText("The Customer has these Special requests for their main course:");

        jToggleButton1.setText("Next Order");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(extrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(extslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extsclbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(decaflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(decafnumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(hottealbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(hotteanumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(coldtealbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(coldteanumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(peachlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(peachnumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lemonlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lemonnumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(mintlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(mintnumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(coffeelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(coffeenumlbl)))
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rblbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbnumlbl))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pepsilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sierralbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pmaxlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ponelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pmaxnumlbl)
                                                    .addComponent(ponenumlbl)
                                                    .addComponent(sierranumlbl)
                                                    .addComponent(mdnumlbl)
                                                    .addComponent(dpnumlbl)
                                                    .addComponent(pepsinumlbl)))))
                                    .addComponent(dessertlbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(frenchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(classlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(houselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbonelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel80)
                                            .addComponent(classnumlbl)
                                            .addComponent(frenchnumlbl)
                                            .addComponent(tbonenumlbl))
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(caesarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sbarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(daysouplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bsouplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bsoupnumlbl)
                                            .addComponent(daysoupnumlbl)
                                            .addComponent(sbarnumlbl)
                                            .addComponent(caesarnumlbl)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(clamlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clamnumlbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(entreelbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(hfslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(vanlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chscakelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hfsnumlbl)
                                            .addComponent(chscakenumlbl)
                                            .addComponent(vannumlbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(banslbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ciclbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(rbflbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbfnumlbl)
                                            .addComponent(bansnumlbl)
                                            .addComponent(cicnumlbl)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(whichtable)
                                        .addGap(18, 18, 18)
                                        .addComponent(tablelbl)
                                        .addGap(64, 64, 64)
                                        .addComponent(whichsection)
                                        .addGap(27, 27, 27)
                                        .addComponent(sectionlbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bufflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sautmushlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nacholbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(96, 96, 96)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(samplelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cwslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(applbl)))
                                    .addComponent(drinkslbl)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(customerrequestlbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jToggleButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whichtable)
                    .addComponent(tablelbl)
                    .addComponent(whichsection)
                    .addComponent(sectionlbl))
                .addGap(18, 18, 18)
                .addComponent(drinkslbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coffeelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coffeenumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decaflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decafnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hottealbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotteanumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coldtealbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coldteanumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peachlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peachnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lemonlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lemonnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mintlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mintnumlbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pepsilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pepsinumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mdnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sierralbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sierranumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pmaxlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pmaxnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ponelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ponenumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rblbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbnumlbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nacholbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bufflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sautmushlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(samplelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cwslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extsclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(customerrequestlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entreelbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbonelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbonenumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frenchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frenchnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(houselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caesarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caesarnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sbarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sbarnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daysouplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daysoupnumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bsouplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsoupnumlbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clamlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clamnumlbl))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dessertlbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chscakelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chscakenumlbl)
                    .addComponent(ciclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cicnumlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hfslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hfsnumlbl)
                    .addComponent(banslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bansnumlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vannumlbl)
                    .addComponent(rbflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbfnumlbl))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {                                            
        System.exit(0);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc="wrapped, again lookandfeel, edit if you so desire ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitchen().setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify
    // <editor-fold defaultstate="collapsed" desc="all the variables wrapped for neatness">
    private javax.swing.JLabel applbl;
    public static javax.swing.JLabel banslbl;
    public static javax.swing.JLabel bansnumlbl;
    public static javax.swing.JLabel bsouplbl;
    public static javax.swing.JLabel bsoupnumlbl;
    public static javax.swing.JLabel bufflbl;
    public static javax.swing.JLabel caesarlbl;
    public static javax.swing.JLabel caesarnumlbl;
    public static javax.swing.JLabel chscakelbl;
    public static javax.swing.JLabel chscakenumlbl;
    public static javax.swing.JLabel ciclbl;
    public static javax.swing.JLabel cicnumlbl;
    public static javax.swing.JLabel clamlbl;
    public static javax.swing.JLabel clamnumlbl;
    public static javax.swing.JLabel classlbl;
    public static javax.swing.JLabel classnumlbl;
    public static javax.swing.JLabel coffeelbl;
    public static javax.swing.JLabel coffeenumlbl;
    public static javax.swing.JLabel coldtealbl;
    public static javax.swing.JLabel coldteanumlbl;
    private javax.swing.JLabel customerrequestlbl;
    public static javax.swing.JLabel cwslbl;
    public static javax.swing.JLabel daysouplbl;
    public static javax.swing.JLabel daysoupnumlbl;
    public static javax.swing.JLabel decaflbl;
    public static javax.swing.JLabel decafnumlbl;
    private javax.swing.JLabel dessertlbl;
    public static javax.swing.JLabel dplbl;
    public static javax.swing.JLabel dpnumlbl;
    private javax.swing.JLabel drinkslbl;
    private javax.swing.JLabel entreelbl;
    public static javax.swing.JLabel extrlbl;
    public static javax.swing.JLabel extsclbl;
    public static javax.swing.JLabel extslbl;
    public static javax.swing.JLabel fflbl;
    public static javax.swing.JLabel frenchlbl;
    public static javax.swing.JLabel frenchnumlbl;
    public static javax.swing.JLabel hfslbl;
    public static javax.swing.JLabel hfsnumlbl;
    public static javax.swing.JLabel hottealbl;
    public static javax.swing.JLabel hotteanumlbl;
    public static javax.swing.JLabel houselbl;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JLabel lemonlbl;
    public static javax.swing.JLabel lemonnumlbl;
    public static javax.swing.JLabel mdlbl;
    public static javax.swing.JLabel mdnumlbl;
    public static javax.swing.JLabel mintlbl;
    public static javax.swing.JLabel mintnumlbl;
    public static javax.swing.JLabel nacholbl;
    public static javax.swing.JLabel peachlbl;
    public static javax.swing.JLabel peachnumlbl;
    public static javax.swing.JLabel pepsilbl;
    public static javax.swing.JLabel pepsinumlbl;
    public static javax.swing.JLabel pmaxlbl;
    public static javax.swing.JLabel pmaxnumlbl;
    public static javax.swing.JLabel ponelbl;
    public static javax.swing.JLabel ponenumlbl;
    public static javax.swing.JLabel rbflbl;
    public static javax.swing.JLabel rbfnumlbl;
    public static javax.swing.JLabel rblbl;
    public static javax.swing.JLabel rbnumlbl;
    public static javax.swing.JTextArea request1lbl;
    public static javax.swing.JTextArea request2lbl;
    public static javax.swing.JLabel samplelbl;
    public static javax.swing.JLabel sautmushlbl;
    public static javax.swing.JLabel sbarlbl;
    public static javax.swing.JLabel sbarnumlbl;
    public static javax.swing.JLabel sectionlbl;
    public static javax.swing.JLabel sierralbl;
    public static javax.swing.JLabel sierranumlbl;
    public static javax.swing.JLabel tablelbl;
    public static javax.swing.JLabel tbonelbl;
    public static javax.swing.JLabel tbonenumlbl;
    public static javax.swing.JLabel vanlbl;
    public static javax.swing.JLabel vannumlbl;
    private javax.swing.JLabel whichsection;
    private javax.swing.JLabel whichtable;
    //</editor-fold>
    // End of variables declaration
}
