/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ordermenu;

import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.AbstractButton;
import javax.swing.Action;
import javax.swing.JTextField;


/**
 *
 * @author Kaleb
 */
public class MenuOrderUI extends javax.swing.JFrame {
        
        
    /**
     * Creates new form MenuOrderUI
     */
    public MenuOrderUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. Thanks -Kaleb
     */
    // <editor-fold defaultstate="collapsed" desc="This code is wrapped and controls the layout edit cautiously">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField22 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tabletxt = new javax.swing.JTextField();
        partytxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        plschooseapplbl = new javax.swing.JLabel();
        nachochk = new javax.swing.JCheckBox();
        buffchk = new javax.swing.JCheckBox();
        sautmushchk = new javax.swing.JCheckBox();
        samplechk = new javax.swing.JCheckBox();
        cwschk = new javax.swing.JCheckBox();
        ffchk = new javax.swing.JCheckBox();
        extrbut = new javax.swing.JRadioButton();
        extsbut = new javax.swing.JRadioButton();
        extscbut = new javax.swing.JRadioButton();
        extrastufflbl = new javax.swing.JLabel();
        multipleapplbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        request1txt = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        plschooseentreelbl = new javax.swing.JLabel();
        tbonechk = new javax.swing.JCheckBox();
        frenchchk = new javax.swing.JCheckBox();
        classchk = new javax.swing.JCheckBox();
        housechk = new javax.swing.JCheckBox();
        caesarchk = new javax.swing.JCheckBox();
        sbarchk = new javax.swing.JCheckBox();
        daysoupchk = new javax.swing.JCheckBox();
        entmenu1lbl = new javax.swing.JLabel();
        entmenu2lbl = new javax.swing.JLabel();
        entmenu3lbl = new javax.swing.JLabel();
        entnum1lbl = new javax.swing.JLabel();
        entnum2lbl = new javax.swing.JLabel();
        bsoupchk = new javax.swing.JCheckBox();
        clamchk = new javax.swing.JCheckBox();
        tbonetxt = new javax.swing.JTextField();
        frenchtxt = new javax.swing.JTextField();
        classtxt = new javax.swing.JTextField();
        housetxt = new javax.swing.JTextField();
        sbartxt = new javax.swing.JTextField();
        caesartxt = new javax.swing.JTextField();
        daysouptxt = new javax.swing.JTextField();
        clamtxt = new javax.swing.JTextField();
        bsouptxt = new javax.swing.JTextField();
        entnum3lbl = new javax.swing.JLabel();
        specialrequestlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        request2txt = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        desmenuitem1lbl = new javax.swing.JLabel();
        dessnum1lbl = new javax.swing.JLabel();
        dessmenu3lbl = new javax.swing.JLabel();
        dessmenu2lbl = new javax.swing.JLabel();
        dessnum3lbl = new javax.swing.JLabel();
        dessnum2lbl = new javax.swing.JLabel();
        chscakechk = new javax.swing.JCheckBox();
        hfschk = new javax.swing.JCheckBox();
        vanchk = new javax.swing.JCheckBox();
        cicchk = new javax.swing.JCheckBox();
        banschk = new javax.swing.JCheckBox();
        rbfchk = new javax.swing.JCheckBox();
        chscakecst = new javax.swing.JLabel();
        hfscst = new javax.swing.JLabel();
        vancst = new javax.swing.JLabel();
        ciccst = new javax.swing.JLabel();
        banscst = new javax.swing.JLabel();
        rbfcst = new javax.swing.JLabel();
        chscaketxt = new javax.swing.JTextField();
        hfstxt = new javax.swing.JTextField();
        vantxt = new javax.swing.JTextField();
        cictxt = new javax.swing.JTextField();
        banstxt = new javax.swing.JTextField();
        rbftxt = new javax.swing.JTextField();
        customersatisfactionlbl = new javax.swing.JLabel();
        plsbedetailedlbl = new javax.swing.JLabel();
        customersubmitbut = new javax.swing.JButton();
        tbonecst = new javax.swing.JLabel();
        frenchcst = new javax.swing.JLabel();
        classiccst = new javax.swing.JLabel();
        housecst = new javax.swing.JLabel();
        caesarcst = new javax.swing.JLabel();
        sbarcst = new javax.swing.JLabel();
        daysoupcst = new javax.swing.JLabel();
        bsoupcst = new javax.swing.JLabel();
        clamcst = new javax.swing.JLabel();
        nachocst = new javax.swing.JLabel();
        buffcst = new javax.swing.JLabel();
        sautmushcst = new javax.swing.JLabel();
        samplecst = new javax.swing.JLabel();
        cwscst = new javax.swing.JLabel();
        ffcst = new javax.swing.JLabel();
        extracst = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        plschoosedrnklbl = new javax.swing.JLabel();
        morethn1drnklbl = new javax.swing.JLabel();
        drnkop1lbl = new javax.swing.JLabel();
        drnknum1lbl = new javax.swing.JLabel();
        coffeechk = new javax.swing.JCheckBox();
        decafchk = new javax.swing.JCheckBox();
        hotteachk = new javax.swing.JCheckBox();
        coldteachk = new javax.swing.JCheckBox();
        coffeetxt = new javax.swing.JTextField();
        decaftxt = new javax.swing.JTextField();
        hotteatxt = new javax.swing.JTextField();
        coldteatxt = new javax.swing.JTextField();
        peachbut = new javax.swing.JRadioButton();
        lemonbut = new javax.swing.JRadioButton();
        mintbut = new javax.swing.JRadioButton();
        peachteatxt = new javax.swing.JTextField();
        lemonteatxt = new javax.swing.JTextField();
        mintteatxt = new javax.swing.JTextField();
        drnkop2lbl = new javax.swing.JLabel();
        drnknum2lbl = new javax.swing.JLabel();
        pepsichk = new javax.swing.JCheckBox();
        dpchk = new javax.swing.JCheckBox();
        mdchk = new javax.swing.JCheckBox();
        sierrachk = new javax.swing.JCheckBox();
        pmaxchk = new javax.swing.JCheckBox();
        ponechk = new javax.swing.JCheckBox();
        rbchk = new javax.swing.JCheckBox();
        mdtxt = new javax.swing.JTextField();
        pepsitxt = new javax.swing.JTextField();
        dptxt = new javax.swing.JTextField();
        sierratxt = new javax.swing.JTextField();
        pmaxtxt = new javax.swing.JTextField();
        ponetxt = new javax.swing.JTextField();
        rbtxt = new javax.swing.JTextField();
        coffeecst = new javax.swing.JLabel();
        decafcst = new javax.swing.JLabel();
        hotteacst = new javax.swing.JLabel();
        coldteacst = new javax.swing.JLabel();
        pepsicst = new javax.swing.JLabel();
        dpcst = new javax.swing.JLabel();
        mdcst = new javax.swing.JLabel();
        sierracst = new javax.swing.JLabel();
        pmaxcst = new javax.swing.JLabel();
        ponecst = new javax.swing.JLabel();
        rbcst = new javax.swing.JLabel();
        sectiontxt = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField22.setText("jTextField22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Section  /  Table", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel1.setText("Customer's Name:");

        jLabel2.setText("Section Customer is in:");

        jLabel3.setText("Table Customer is at:");

        jLabel4.setText("Party Size at Table:");

        tabletxt.setFocusable(false);

        partytxt.setFocusable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appetizer Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 14))); // NOI18N

        plschooseapplbl.setText("Please select an Appetizer ");

        nachochk.setText("Nacho's");

        buffchk.setText("Buffalo Wings");

        sautmushchk.setText("Sautéed Mushrooms");

        samplechk.setText("Sample Platter");

        cwschk.setText("Chips with Salsa and Sour Cream");

        ffchk.setText("French Fries");

        extrbut.setText("Extra Ranch Dip");

        extsbut.setText("Extra Salsa");

        extscbut.setText("Extra Sour Cream");

        extrastufflbl.setText("Would You Like any Extra Dip?");

        multipleapplbl.setText("If You would like more than one of the same Appetizer Please Say which one and How many Below");

        jScrollPane1.setViewportView(request1txt);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entree Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 14))); // NOI18N
        customerName.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerNameKeyPressed(evt);
            }
        });

        plschooseentreelbl.setText("Please Select an Entrée");

        tbonechk.setText("T-Bone Steak");

        frenchchk.setText("French Dip Sandwhich");

        classchk.setText("Classic Burger");

        housechk.setText("House Salad");

        caesarchk.setText("Caesar Salad");

        sbarchk.setText("Salad Bar");

        daysoupchk.setText("Soup of the Day");

        entmenu1lbl.setText("Menu Item");

        entmenu2lbl.setText("Menu Item");

        entmenu3lbl.setText("Menu Item");

        entnum1lbl.setText("How Many?");

        entnum2lbl.setText("How Many?");

        bsoupchk.setText("Broccoli Soup");

        clamchk.setText("Clam Chowder");

        entnum3lbl.setText("How Many?");

        specialrequestlbl.setText("Do you have any speacial requests for your meal?");

        jScrollPane2.setViewportView(request2txt);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dessert Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 14))); // NOI18N

        desmenuitem1lbl.setText("Menu Item");

        dessnum1lbl.setText("How Many?");

        dessmenu3lbl.setText("Menu Item");

        dessmenu2lbl.setText("Menu Item");

        dessnum3lbl.setText("How Many?");

        dessnum2lbl.setText("How Many?");

        chscakechk.setText("Cheesecake");

        hfschk.setText("Hot Fudge Sunday");

        vanchk.setText("Vanilla Ice Cream");

        cicchk.setText("Chocolate Ice Cream");

        banschk.setText("Banana Split");

        rbfchk.setText("Root Beer Float");

        chscakecst.setText("5.00");

        hfscst.setText("5.00");

        vancst.setText("3.30");

        ciccst.setText("3.30");

        banscst.setText("5.00");

        rbfcst.setText("3.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desmenuitem1lbl))
                    .addComponent(chscakechk)
                    .addComponent(hfschk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dessnum1lbl)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(banschk)
                                        .addComponent(rbfchk))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(banstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(rbftxt))
                                    .addGap(17, 17, 17))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(dessmenu3lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dessnum3lbl))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hfstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(chscaketxt))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(chscakecst))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(hfscst)
                                    .addGap(163, 163, 163))))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(dessmenu2lbl)
                                .addGap(61, 61, 61)
                                .addComponent(dessnum2lbl))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cicchk)
                                    .addComponent(vanchk))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(vantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(vancst))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(cictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(ciccst)))))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbfcst)
                            .addComponent(banscst))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desmenuitem1lbl)
                    .addComponent(dessnum1lbl)
                    .addComponent(dessmenu2lbl)
                    .addComponent(dessnum2lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chscakechk)
                    .addComponent(vanchk)
                    .addComponent(chscakecst)
                    .addComponent(vancst)
                    .addComponent(chscaketxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hfschk)
                    .addComponent(cicchk)
                    .addComponent(hfscst)
                    .addComponent(ciccst)
                    .addComponent(hfstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cictxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dessmenu3lbl)
                    .addComponent(dessnum3lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banschk)
                    .addComponent(banscst)
                    .addComponent(banstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfchk)
                    .addComponent(rbfcst)
                    .addComponent(rbftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        customersatisfactionlbl.setText(" Our customers satisfaction is our number one priority!");

        plsbedetailedlbl.setText(" Please be as detailed as you like.");

        customersubmitbut.setText("Submit Order");
        customersubmitbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersubmitbutMouseClicked(evt);
            }
        });

        tbonecst.setText("19.20");

        frenchcst.setText("10.50");

        classiccst.setText("8.00");

        housecst.setText("5.50");

        caesarcst.setText("6.00");

        sbarcst.setText("5.50");

        daysoupcst.setText("3.00");

        bsoupcst.setText("3.00");

        clamcst.setText("5.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classchk)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(tbonechk)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(frenchchk)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(frenchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(classtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(130, 130, 130)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(entmenu2lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(entnum2lbl))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(caesarchk)
                                                .addGap(18, 18, 18)
                                                .addComponent(caesartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(housechk)
                                            .addGap(22, 22, 22)
                                            .addComponent(housetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sbarchk)
                                        .addGap(36, 36, 36)
                                        .addComponent(sbartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(customersatisfactionlbl)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(plsbedetailedlbl))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(entmenu3lbl)
                                                    .addGap(31, 31, 31))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bsoupchk)
                                                    .addComponent(daysoupchk)
                                                    .addComponent(clamchk)
                                                    .addComponent(tbonecst)
                                                    .addComponent(frenchcst)
                                                    .addComponent(classiccst)))
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(bsouptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(bsoupcst))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(clamtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(clamcst))
                                                .addComponent(entnum3lbl)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(daysouptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(daysoupcst))))
                                        .addComponent(specialrequestlbl)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housecst)
                            .addComponent(caesarcst)
                            .addComponent(sbarcst)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(entmenu1lbl)
                        .addGap(57, 57, 57)
                        .addComponent(entnum1lbl))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(plschooseentreelbl))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(customersubmitbut)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(plschooseentreelbl)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entmenu1lbl)
                    .addComponent(entmenu2lbl)
                    .addComponent(entnum1lbl)
                    .addComponent(entnum2lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbonechk)
                    .addComponent(housechk)
                    .addComponent(tbonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(housetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbonecst)
                    .addComponent(housecst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frenchchk)
                    .addComponent(caesarchk)
                    .addComponent(frenchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caesartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frenchcst)
                    .addComponent(caesarcst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classchk)
                    .addComponent(sbarchk)
                    .addComponent(classtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classiccst)
                    .addComponent(sbarcst))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entmenu3lbl)
                    .addComponent(entnum3lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysoupchk)
                    .addComponent(daysouptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysoupcst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsoupchk)
                    .addComponent(bsouptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsoupcst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clamchk)
                    .addComponent(clamtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clamcst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(specialrequestlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plsbedetailedlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customersatisfactionlbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customersubmitbut))
        );

        nachocst.setText("5.50");

        buffcst.setText("5.50");

        sautmushcst.setText("3.00");

        samplecst.setText("5.00");

        cwscst.setText("6.60");

        ffcst.setText("2.50");

        extracst.setText(".50 ");

        jLabel23.setText("per extra:");

        jLabel5.setText("If more than one appetizer is requested, cost will be added to the total when your check arrives ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(extrbut)
                        .addGap(55, 55, 55)
                        .addComponent(extsbut)
                        .addGap(18, 18, 18)
                        .addComponent(extscbut)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(nachochk)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(169, 169, 169)
                                                .addComponent(plschooseapplbl))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(nachocst))
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addGap(34, 34, 34)
                                                        .addComponent(buffcst)))
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sautmushchk)
                                                    .addComponent(samplechk))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(samplecst)
                                                    .addComponent(sautmushcst)))))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(extracst))
                                        .addComponent(buffchk))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(extrastufflbl))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(multipleapplbl))))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ffchk)
                                    .addComponent(cwschk))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cwscst)
                            .addComponent(ffcst))
                        .addGap(61, 61, 61)))
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(plschooseapplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nachochk)
                    .addComponent(sautmushchk)
                    .addComponent(cwschk)
                    .addComponent(nachocst)
                    .addComponent(sautmushcst)
                    .addComponent(cwscst))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buffchk)
                    .addComponent(samplechk)
                    .addComponent(ffchk)
                    .addComponent(buffcst)
                    .addComponent(samplecst)
                    .addComponent(ffcst))
                .addGap(6, 6, 6)
                .addComponent(extrastufflbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extrbut)
                    .addComponent(extsbut)
                    .addComponent(extscbut)
                    .addComponent(extracst)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multipleapplbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drink Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 14))); // NOI18N
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        plschoosedrnklbl.setText("Please select a Drink from the following Menu");

        morethn1drnklbl.setText("If more than one customer would like the same drink please enter the number of desired drinks after the check box");

        drnkop1lbl.setText("Drink Options");

        drnknum1lbl.setText("How many would you Like?");

        coffeechk.setText("Coffee");

        decafchk.setText("De-Caf Coffee");

        hotteachk.setText("Hot Tea");

        coldteachk.setText("Cold Tea");

        peachbut.setText("Peach Tea");

        lemonbut.setText("Lemon Tea");

        mintbut.setText("Mint Tea");

        drnkop2lbl.setText("Soda Options");

        drnknum2lbl.setText("How many would you Like?");

        pepsichk.setText("Pepsi");

        dpchk.setText("Diet Pepsi");

        mdchk.setText("Mountain Dew");

        sierrachk.setText("Sierra Mist");

        pmaxchk.setText("Pepsi Max");

        ponechk.setText("Pepsi One");

        rbchk.setText("Root Beer");

        coffeecst.setText("0.75");

        decafcst.setText("0.75");

        hotteacst.setText("1.50");

        coldteacst.setText("1.50");

        pepsicst.setText("1.00");

        dpcst.setText("1.00");

        mdcst.setText("1.00");

        sierracst.setText("1.00");

        pmaxcst.setText("1.00");

        ponecst.setText("1.00");

        rbcst.setText("1.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(drnkop1lbl)
                                .addGap(18, 18, 18)
                                .addComponent(drnknum1lbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coffeechk)
                                    .addComponent(decafchk)
                                    .addComponent(hotteachk)
                                    .addComponent(coldteachk)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lemonbut)
                                            .addComponent(peachbut)
                                            .addComponent(mintbut))))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(peachteatxt)
                                    .addComponent(coldteatxt)
                                    .addComponent(hotteatxt)
                                    .addComponent(decaftxt)
                                    .addComponent(coffeetxt)
                                    .addComponent(lemonteatxt)
                                    .addComponent(mintteatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coffeecst)
                                    .addComponent(decafcst)
                                    .addComponent(hotteacst)
                                    .addComponent(coldteacst))))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(drnkop2lbl)
                                .addGap(18, 18, 18)
                                .addComponent(drnknum2lbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pepsichk)
                                    .addComponent(dpchk)
                                    .addComponent(mdchk)
                                    .addComponent(sierrachk)
                                    .addComponent(pmaxchk)
                                    .addComponent(ponechk)
                                    .addComponent(rbchk))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mdtxt)
                                    .addComponent(ponetxt)
                                    .addComponent(pmaxtxt)
                                    .addComponent(sierratxt)
                                    .addComponent(dptxt)
                                    .addComponent(pepsitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtxt))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pepsicst)
                                    .addComponent(dpcst)
                                    .addComponent(mdcst)
                                    .addComponent(sierracst)
                                    .addComponent(pmaxcst)
                                    .addComponent(ponecst)
                                    .addComponent(rbcst)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(plschoosedrnklbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(morethn1drnklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(plschoosedrnklbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(morethn1drnklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drnkop1lbl)
                    .addComponent(drnknum1lbl)
                    .addComponent(drnkop2lbl)
                    .addComponent(drnknum2lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffeechk)
                    .addComponent(coffeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsichk)
                    .addComponent(pepsitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffeecst)
                    .addComponent(pepsicst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decafchk)
                    .addComponent(decaftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpchk)
                    .addComponent(dptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decafcst)
                    .addComponent(dpcst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hotteachk)
                            .addComponent(hotteatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotteacst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coldteachk)
                            .addComponent(coldteatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coldteacst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peachbut)
                            .addComponent(peachteatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lemonteatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lemonbut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mintteatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mintbut)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdchk)
                            .addComponent(mdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mdcst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sierrachk)
                            .addComponent(sierratxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sierracst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pmaxchk)
                            .addComponent(pmaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pmaxcst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ponechk)
                            .addComponent(ponetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ponecst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbchk)
                            .addComponent(rbtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbcst))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        sectiontxt.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(partytxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(customerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tabletxt)
                            .addComponent(sectiontxt, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sectiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tabletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(partytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1987, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void customersubmitbutMouseClicked(java.awt.event.MouseEvent evt) {                                               
        setVisible(false);
        new Thankyou().setVisible(true);
        try{
        calculatecost();
        }catch(java.lang.NumberFormatException ex){
            setVisible(true);
            new WoopsException().setVisible(true);
        }
        String costaftercalculation;
        costaftercalculation = Double.toString(calculatecost());
        Thankyou.totalcostlbl.setText(costaftercalculation);
          //if(coffeechk.isSelected()){
              //Kitchen.drinklist.setText(coffeechk.getText());
          //}
    }
    private void customerNameKeyPressed(java.awt.event.KeyEvent evt) {                                    
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            customerName.setText(customerName.getText());
            customerName.transferFocus();
        }
    }
    public double calculatecost(){
        /* 
         * I know all this is a bit redundant but unfortunately unless I rename all my JTextFields to be Textfield1, 2, 3 etc I can not run them through a simple for loop to check all of them for checks and text etc. I had to name them specific for the purpose of organizing the kitchen class so i chose redundant code over for loops to make anyone else that has to maintain this code have a lot less of a headache.
         */
        // <editor-fold defaultstate="collapsed" desc="I wrapped this as well for neatness">
        String coffeeval;
        String decafval;
        String hotteaval;
        String coldteaval;
        String pepsival;
        String dpval;
        String mdval;
        String sierraval;
        String pmaxval;
        String poneval;
        String rbval;
        String tboneval;
        String frenchval;
        String classval;
        String houseval;
        String caesarval;
        String sbarval;
        String daysoupval;
        String bsoupval;
        String clamval;
        String chscakeval;
        String hfsval;
        String vanval;
        String cicval;
        String bansval;
        String rbfval;
        double coffeenum;
        double decafnum;
        double hotteanum;
        double coldteanum;
        double pepsinum;
        double dpnum;
        double mdnum;
        double sierranum;
        double pmaxnum;
        double ponenum;
        double rbnum;
        double tbonenum;
        double frenchnum;
        double classnum;
        double housenum;
        double caesarnum;
        double sbarnum;
        double daysoupnum;
        double bsoupnum;
        double clamnum;
        double chscakenum;
        double hfsnum;
        double vannum;
        double cicnum;
        double bansnum;
        double rbfnum;
        double cost;
        cost = 0;
        if(coffeechk.isSelected() && coffeetxt.getText().equals("")){
            cost += 0.75;
        }
        else if(coffeechk.isSelected() && coffeetxt.getText()!=(null)){
        coffeeval = coffeetxt.getText();
        coffeenum = Double.parseDouble(coffeeval);
        cost += (0.75 * coffeenum);
        }
        
        if(decafchk.isSelected() && decaftxt.getText().equals("")){
            cost += 0.75;
        }
        else if(decafchk.isSelected() && decaftxt.getText()!=(null)){
        decafval = decaftxt.getText();
        decafnum = Double.parseDouble(decafval);
        cost += (0.75 * decafnum);
        }
        if(hotteachk.isSelected() && hotteatxt.getText().equals("")){
            cost += 1.50;
        }
        else if(hotteachk.isSelected() && hotteatxt.getText()!=(null)){
        hotteaval = hotteatxt.getText();
        hotteanum = Double.parseDouble(hotteaval);
        cost += (1.50 * hotteanum);
        }
        if(coldteachk.isSelected() && coldteatxt.getText().equals("")){
            cost += 1.50;
        }
        else if(coldteachk.isSelected() && coldteatxt.getText()!=(null)){
        coldteaval = coldteatxt.getText();
        coldteanum = Double.parseDouble(coldteaval);
        cost += (1.50 * coldteanum);
        }
        if(pepsichk.isSelected() && pepsitxt.getText().equals("")){
            cost += 1.00;
        }
        else if(pepsichk.isSelected() && pepsitxt.getText()!=(null)){
        pepsival = pepsitxt.getText();
        pepsinum = Double.parseDouble(pepsival);
        cost += (1.00 * pepsinum);
        }
        if(dpchk.isSelected() && dptxt.getText().equals("")){
            cost += 1.00;
        }
        else if(dpchk.isSelected() && dptxt.getText()!=(null)){
        dpval = dptxt.getText();
        dpnum = Double.parseDouble(dpval);
        cost += (1.00 * dpnum);
        }
        if(mdchk.isSelected() && mdtxt.getText().equals("")){
            cost += 1.00;
        }
        else if(mdchk.isSelected() && mdtxt.getText()!=(null)){
        mdval = mdtxt.getText();
        mdnum = Double.parseDouble(mdval);
        cost += (1.00 * mdnum);
        }
        if(sierrachk.isSelected() && sierratxt.getText().equals("")){
            cost += 1.00;
        }
        else if(sierrachk.isSelected() && sierratxt.getText()!=(null)){
        sierraval = sierratxt.getText();
        sierranum = Double.parseDouble(sierraval);
        cost += (1.00 * sierranum);
        }
        if(pmaxchk.isSelected() && pmaxtxt.getText().equals("")){
            cost += 1.00;
        }
        else if(pmaxchk.isSelected() && pmaxtxt.getText()!=(null)){
        pmaxval = pmaxtxt.getText();
        pmaxnum = Double.parseDouble(pmaxval);
        cost += (1.00 * pmaxnum);
        }
        if(ponechk.isSelected() && ponetxt.getText().equals("")){
            cost += 1.00;
        }
        else if(ponechk.isSelected() && ponetxt.getText()!=(null)){
        poneval = ponetxt.getText();
        ponenum = Double.parseDouble(poneval);
        cost += (1.00 * ponenum);
        }
        if(rbchk.isSelected() && rbtxt.getText().equals("")){
            cost += 1.00;
        }
        else if(rbchk.isSelected() && rbtxt.getText()!=(null)){
        rbval = rbtxt.getText();
        rbnum = Double.parseDouble(rbval);
        cost += (1.00 * rbnum);
        }
        if(nachochk.isSelected()){
            cost += 5.50;
        }
        
        if(buffchk.isSelected()){
            cost += 5.50;
        }
        
        if(sautmushchk.isSelected()){
            cost += 3.00;
        }
        
        if(samplechk.isSelected()){
            cost += 5.00;
        }
        
        if(cwschk.isSelected()){
            cost += 6.60;
        }
        
        if(ffchk.isSelected()){
            cost += 2.50;
        }
        
        if(extrbut.isSelected()){
            cost += 0.50;
        }
        
        if(extsbut.isSelected()){
            cost += 0.50;
        }
        
        if(extscbut.isSelected()){
            cost += 0.50;
        }
        
        if(tbonechk.isSelected() && tbonetxt.getText().equals("")){
            cost += 19.20;
        }
        else if(tbonechk.isSelected() && tbonetxt.getText()!=(null)){
        tboneval = tbonetxt.getText();
        tbonenum = Double.parseDouble(tboneval);
            cost += (19.20 * tbonenum);
        }
        if(frenchchk.isSelected() && frenchtxt.getText().equals("")){
            cost += 10.50;
        }
        else if(frenchchk.isSelected() && frenchtxt.getText()!=(null)){
        frenchval = frenchtxt.getText();
        frenchnum = Double.parseDouble(frenchval);
            cost += (10.50 * frenchnum);
        }
        if(classchk.isSelected() && classtxt.getText().equals("")){
            cost += 8.00;
        }
        else if(classchk.isSelected() && classtxt.getText()!=(null)){
        classval = classtxt.getText();
        classnum = Double.parseDouble(classval);
            cost += (8.00 * classnum);
        }
        if(housechk.isSelected() && housetxt.getText().equals("")){
            cost += 5.50;
        }
        else if(housechk.isSelected() && housetxt.getText()!=(null)){
        houseval = housetxt.getText();
        housenum = Double.parseDouble(houseval);
            cost += (5.50 * housenum);
        }
        if(caesarchk.isSelected() && caesartxt.getText().equals("")){
            cost += 6.00;
        }
        else if(caesarchk.isSelected() && caesartxt.getText()!=(null)){
        caesarval = caesartxt.getText();
        caesarnum = Double.parseDouble(caesarval);
            cost += (6.00 * caesarnum);
        }
        if(sbarchk.isSelected() && sbartxt.getText().equals("")){
            cost += 5.50;
        }
        else if(sbarchk.isSelected() && sbartxt.getText()!=(null)){
        sbarval = sbartxt.getText();
        sbarnum = Double.parseDouble(sbarval);
            cost += (5.50 * sbarnum);
        }
        if(daysoupchk.isSelected() && daysouptxt.getText().equals("")){
            cost += 3.00;
        }
        else if(daysoupchk.isSelected() && daysouptxt.getText()!=(null)){
        daysoupval = daysouptxt.getText();
        daysoupnum = Double.parseDouble(daysoupval);
            cost += (3.00 * daysoupnum);
        }
        if(bsoupchk.isSelected() && bsouptxt.getText().equals("")){
            cost += 3.00;
        }
        else if(bsoupchk.isSelected() && bsouptxt.getText()!=(null)){
        bsoupval = bsouptxt.getText();
        bsoupnum = Double.parseDouble(bsoupval);
            cost += (3.00 * bsoupnum);
        }
        if(clamchk.isSelected() && clamtxt.getText().equals("")){
            cost += 5.00;
        }
        else if(clamchk.isSelected() && clamtxt.getText()!=(null)){
        clamval = clamtxt.getText();
        clamnum = Double.parseDouble(clamval);
            cost += (5.00 * clamnum);
        }
        //I can't figure out why but for some strange reason, all of the dessert items throw an exception if the box is checked, and the JTextField is not filled in, i spent a lot of time trying to figure out why and could not so just added a try catch to the calculatecost() method. If i was writing for a real resteraunt I would of course resolve this issue before giving them the program. OMG, I had for got to tag the text fields as public STATIC, just put static in and now they're all working fine with no exceptions being thrown.
        
        if(chscakechk.isSelected() && chscaketxt.getText().equals("")){
            cost += 5.00;
        }
        else if(chscakechk.isSelected() && chscaketxt.getText()!=(null)){
        chscakeval = chscaketxt.getText();
        chscakenum = Double.parseDouble(chscakeval);
            cost += (5.00 * chscakenum);
        }
        if(hfschk.isSelected() && hfstxt.getText().equals("")){
            cost += 5.00;
        }
        else if(hfschk.isSelected() && hfstxt.getText()!=(null)){
        hfsval = hfstxt.getText();
        hfsnum = Double.parseDouble(hfsval);
            cost += (5.00 * hfsnum);
        }
        if(vanchk.isSelected() && vantxt.getText().equals("")){
            cost += 3.30;
        }
        else if(vanchk.isSelected() && vantxt.getText()!=(null)){
        vanval = vantxt.getText();
        vannum = Double.parseDouble(vanval);
            cost += (3.30 * vannum);
        }
        if(cicchk.isSelected() && cictxt.getText().equals("")){
            cost+= 3.30;
        }
        else if(cicchk.isSelected() && cictxt.getText()!=(null)){
        cicval = cictxt.getText();
        cicnum = Double.parseDouble(cicval);
            cost += (3.30 * cicnum);
        }
        if(banschk.isSelected() && banstxt.getText().equals("")){
            cost += 5.00;
        }
        else if(banschk.isSelected() && banstxt.getText()!=(null)){
        bansval = banstxt.getText();
        bansnum = Double.parseDouble(bansval);
            cost += (5.00 * bansnum);
        }
        if(rbfchk.isSelected() && rbftxt.getText().equals("")){
            cost += 3.00;
        }
        else if(rbfchk.isSelected() && rbftxt.getText()!=(null)){
        rbfval = rbftxt.getText();
        rbfnum = Double.parseDouble(rbfval);
            cost += (3.00 * rbfnum);
        }
        cost = Math.round(cost);
        return cost;
        // </editor-fold>
    }
    
    public static void run() {
        //<editor-fold defaultstate="collapsed" desc=" Again look and feel code, edit if you so desire ">
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* 
         * Create and display the form when called by the tableAndSection class
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableAndSection().setVisible(true);    
            }
        });
    }
    // Variables declaration, these are all the variables used in
    //this class - modify cautiously
    //<editor-fold defaultstate="collapsed" desc="wrapped for neatness">
    public static javax.swing.JCheckBox banschk;
    public static javax.swing.JLabel banscst;
    public static javax.swing.JTextField banstxt;
    public static javax.swing.JCheckBox bsoupchk;
    public static javax.swing.JLabel bsoupcst;
    public static javax.swing.JTextField bsouptxt;
    public static javax.swing.JCheckBox buffchk;
    public static javax.swing.JLabel buffcst;
    public static javax.swing.JCheckBox caesarchk;
    public static javax.swing.JLabel caesarcst;
    public static javax.swing.JTextField caesartxt;
    public static javax.swing.JCheckBox chscakechk;
    public static javax.swing.JLabel chscakecst;
    public static javax.swing.JTextField chscaketxt;
    public static javax.swing.JCheckBox cicchk;
    public static javax.swing.JLabel ciccst;
    public static javax.swing.JTextField cictxt;
    public static javax.swing.JCheckBox clamchk;
    public static javax.swing.JLabel clamcst;
    public static javax.swing.JTextField clamtxt;
    public static javax.swing.JCheckBox classchk;
    public static javax.swing.JLabel classiccst;
    public static javax.swing.JTextField classtxt;
    public static javax.swing.JCheckBox coffeechk;
    public static javax.swing.JLabel coffeecst;
    public static javax.swing.JTextField coffeetxt;
    public static javax.swing.JCheckBox coldteachk;
    public static javax.swing.JLabel coldteacst;
    public static javax.swing.JTextField coldteatxt;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel customersatisfactionlbl;
    private javax.swing.JButton customersubmitbut;
    public static javax.swing.JCheckBox cwschk;
    public static javax.swing.JLabel cwscst;
    public static javax.swing.JCheckBox daysoupchk;
    public static javax.swing.JLabel daysoupcst;
    public static javax.swing.JTextField daysouptxt;
    public static javax.swing.JCheckBox decafchk;
    public static javax.swing.JLabel decafcst;
    public static javax.swing.JTextField decaftxt;
    private javax.swing.JLabel desmenuitem1lbl;
    private javax.swing.JLabel dessmenu2lbl;
    private javax.swing.JLabel dessmenu3lbl;
    private javax.swing.JLabel dessnum1lbl;
    private javax.swing.JLabel dessnum2lbl;
    private javax.swing.JLabel dessnum3lbl;
    public static javax.swing.JCheckBox dpchk;
    public static javax.swing.JLabel dpcst;
    public static javax.swing.JTextField dptxt;
    private javax.swing.JLabel drnknum1lbl;
    private javax.swing.JLabel drnknum2lbl;
    private javax.swing.JLabel drnkop1lbl;
    private javax.swing.JLabel drnkop2lbl;
    private javax.swing.JLabel entmenu1lbl;
    private javax.swing.JLabel entmenu2lbl;
    private javax.swing.JLabel entmenu3lbl;
    private javax.swing.JLabel entnum1lbl;
    private javax.swing.JLabel entnum2lbl;
    private javax.swing.JLabel entnum3lbl;
    public static javax.swing.JLabel extracst;
    private javax.swing.JLabel extrastufflbl;
    public static javax.swing.JRadioButton extrbut;
    public static javax.swing.JRadioButton extsbut;
    public static javax.swing.JRadioButton extscbut;
    public static javax.swing.JCheckBox ffchk;
    public static javax.swing.JLabel ffcst;
    public static javax.swing.JCheckBox frenchchk;
    public static javax.swing.JLabel frenchcst;
    public static javax.swing.JTextField frenchtxt;
    public static javax.swing.JCheckBox hfschk;
    public static javax.swing.JLabel hfscst;
    public static javax.swing.JTextField hfstxt;
    public static javax.swing.JCheckBox hotteachk;
    public static javax.swing.JLabel hotteacst;
    public static javax.swing.JTextField hotteatxt;
    public static javax.swing.JCheckBox housechk;
    public static javax.swing.JLabel housecst;
    public static javax.swing.JTextField housetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField22;
    public static javax.swing.JRadioButton lemonbut;
    public static javax.swing.JTextField lemonteatxt;
    public static javax.swing.JCheckBox mdchk;
    public static javax.swing.JLabel mdcst;
    public static javax.swing.JTextField mdtxt;
    public static javax.swing.JRadioButton mintbut;
    public static javax.swing.JTextField mintteatxt;
    private javax.swing.JLabel morethn1drnklbl;
    private javax.swing.JLabel multipleapplbl;
    public static javax.swing.JCheckBox nachochk;
    public static javax.swing.JLabel nachocst;
    public static javax.swing.JTextField partytxt;
    public static javax.swing.JRadioButton peachbut;
    public static javax.swing.JTextField peachteatxt;
    public static javax.swing.JCheckBox pepsichk;
    public static javax.swing.JLabel pepsicst;
    public static javax.swing.JTextField pepsitxt;
    private javax.swing.JLabel plsbedetailedlbl;
    private javax.swing.JLabel plschooseapplbl;
    private javax.swing.JLabel plschoosedrnklbl;
    private javax.swing.JLabel plschooseentreelbl;
    public static javax.swing.JCheckBox pmaxchk;
    public static javax.swing.JLabel pmaxcst;
    public static javax.swing.JTextField pmaxtxt;
    public static javax.swing.JCheckBox ponechk;
    public static javax.swing.JLabel ponecst;
    public static javax.swing.JTextField ponetxt;
    public static javax.swing.JCheckBox rbchk;
    public static javax.swing.JLabel rbcst;
    public static javax.swing.JCheckBox rbfchk;
    public static javax.swing.JLabel rbfcst;
    public static javax.swing.JTextField rbftxt;
    public static javax.swing.JTextField rbtxt;
    public static javax.swing.JTextPane request1txt;
    public static javax.swing.JTextPane request2txt;
    public static javax.swing.JCheckBox samplechk;
    public static javax.swing.JLabel samplecst;
    public static javax.swing.JCheckBox sautmushchk;
    public static javax.swing.JLabel sautmushcst;
    public static javax.swing.JCheckBox sbarchk;
    public static javax.swing.JLabel sbarcst;
    public static javax.swing.JTextField sbartxt;
    public static javax.swing.JFormattedTextField sectiontxt;
    public static javax.swing.JCheckBox sierrachk;
    public static javax.swing.JLabel sierracst;
    public static javax.swing.JTextField sierratxt;
    private javax.swing.JLabel specialrequestlbl;
    public static javax.swing.JTextField tabletxt;
    public static javax.swing.JCheckBox tbonechk;
    public static javax.swing.JLabel tbonecst;
    public static javax.swing.JTextField tbonetxt;
    public static javax.swing.JCheckBox vanchk;
    public static javax.swing.JLabel vancst;
    public static javax.swing.JTextField vantxt;
    //</editor-fold>
    // End of variables declaration
}
