package statscalc;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kaleb
 */
public class statsCalcGUI extends javax.swing.JFrame {

    /**
     * Creates new form statsCalcGUI
     */
    public statsCalcGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayDataTxt = new javax.swing.JTextArea();
        meanTxt = new javax.swing.JTextField();
        medianTxt = new javax.swing.JTextField();
        Q3Txt = new javax.swing.JTextField();
        Q1Txt = new javax.swing.JTextField();
        meanLbl = new javax.swing.JLabel();
        medianLbl = new javax.swing.JLabel();
        Q1Lbl = new javax.swing.JLabel();
        Q3Lbl = new javax.swing.JLabel();
        rangeTxt = new javax.swing.JTextField();
        rangeLbl = new javax.swing.JLabel();
        enterDataTxt = new javax.swing.JTextField();
        enterDataLbl = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        IQRTxt = new javax.swing.JTextField();
        IRQLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sortedTxt = new javax.swing.JTextArea();
        stdDevLbl = new javax.swing.JLabel();
        stdDevTxt = new javax.swing.JTextField();
        fiveNumSumTxt = new javax.swing.JTextField();
        fiuveNumSumLbl = new javax.swing.JLabel();
        lowOutLbl = new javax.swing.JLabel();
        upOutLbl = new javax.swing.JLabel();
        lowOutTxt = new javax.swing.JTextField();
        upOutTxt = new javax.swing.JTextField();
        resetBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayDataTxt.setColumns(20);
        displayDataTxt.setRows(5);
        displayDataTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                displayDataTxtFocusGained(evt);
            }
        });
        displayDataTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayDataTxtKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(displayDataTxt);

        meanTxt.setFocusable(false);
        meanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meanTxtActionPerformed(evt);
            }
        });

        medianTxt.setFocusable(false);
        medianTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianTxtActionPerformed(evt);
            }
        });

        Q3Txt.setFocusable(false);
        Q3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3TxtActionPerformed(evt);
            }
        });

        Q1Txt.setFocusable(false);
        Q1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1TxtActionPerformed(evt);
            }
        });

        meanLbl.setText("Mean (always pulled to skewed side)");

        medianLbl.setText("Median (Q2) middle of the table");

        Q1Lbl.setText("Q1 middle of first 50%");

        Q3Lbl.setText("Q3 middle of last 50%");

        rangeTxt.setFocusable(false);
        rangeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeTxtActionPerformed(evt);
            }
        });

        rangeLbl.setText("Range  (Max - Min)");

        enterDataTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterDataTxtFocusGained(evt);
            }
        });
        enterDataTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterDataTxtKeyPressed(evt);
            }
        });

        enterDataLbl.setText("Enter Data Value then hit enter, values can be entered in any order");

        calculate.setText("Calculate Everything");
        calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateMouseClicked(evt);
            }
        });

        IQRTxt.setFocusable(false);

        IRQLbl.setText("IQR");

        sortedTxt.setColumns(20);
        sortedTxt.setRows(5);
        jScrollPane2.setViewportView(sortedTxt);

        stdDevLbl.setText("Standard Deviation");

        stdDevTxt.setFocusable(false);

        fiveNumSumTxt.setFocusable(false);

        fiuveNumSumLbl.setText("5 number summary");

        lowOutLbl.setText("Lower Outlier");

        upOutLbl.setText("Upper Outlier");

        lowOutTxt.setFocusable(false);

        upOutTxt.setFocusable(false);

        resetBut.setText("RESET ALL");
        resetBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rangeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Q1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lowOutTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lowOutLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rangeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IRQLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(IQRTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stdDevLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stdDevTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(upOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(upOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Q1Txt)
                                    .addComponent(medianLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(medianTxt)
                                    .addComponent(Q3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Q3Txt)
                                    .addComponent(fiuveNumSumLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fiveNumSumTxt)
                                    .addComponent(meanLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(meanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 375, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetBut)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enterDataLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enterDataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterDataLbl)
                .addGap(5, 5, 5)
                .addComponent(enterDataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculate)
                    .addComponent(resetBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1Lbl)
                    .addComponent(rangeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianLbl)
                    .addComponent(IRQLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IQRTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q3Lbl)
                    .addComponent(stdDevLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdDevTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiuveNumSumLbl)
                    .addComponent(lowOutLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiveNumSumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanLbl)
                    .addComponent(upOutLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meanTxtActionPerformed

    private void medianTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medianTxtActionPerformed

    private void Q3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q3TxtActionPerformed

    private void Q1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1TxtActionPerformed

    private void displayDataTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayDataTxtKeyPressed
    }//GEN-LAST:event_displayDataTxtKeyPressed

    private void enterDataTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterDataTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double add = Double.parseDouble(enterDataTxt.getText());
            enterDataTxt.setText(enterDataTxt.getText());
            displayDataTxt.append(enterDataTxt.getText() + "\n");
            data.add(add);
            displayDataTxt.requestFocus();
            TestSorting.run();
        }
    }//GEN-LAST:event_enterDataTxtKeyPressed

    private void displayDataTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_displayDataTxtFocusGained
        enterDataTxt.requestFocus();
    }//GEN-LAST:event_displayDataTxtFocusGained

    private void enterDataTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterDataTxtFocusGained
        enterDataTxt.setText("");
    }//GEN-LAST:event_enterDataTxtFocusGained

    private void calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseClicked
        calcMean();
        calcMedian();
        calcRange();
        calcIQR();
        calcStdDev();
        calcFiveNumSum();
        calcLowOut();
        calcUpOut();
    }//GEN-LAST:event_calculateMouseClicked

    private void rangeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangeTxtActionPerformed

    private void resetButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButMouseClicked
        statsCalcGUI.data = new ArrayList<>();
        statsCalcGUI.sortedData = new double[data.size()];
        displayDataTxt.setText("");
        sortedTxt.setText("");
        enterDataTxt.setText("");
        rangeTxt.setText("");
        Q1Txt.setText("");
        IQRTxt.setText("");
        medianTxt.setText("");
        stdDevTxt.setText("");
        Q3Txt.setText("");
        lowOutTxt.setText("");
        fiveNumSumTxt.setText("");
        upOutTxt.setText("");
        meanTxt.setText("");
    }//GEN-LAST:event_resetButMouseClicked

    public void calcMean() {
        for (int i = 0; i < sortedData.length; i++) {
            total += sortedData[i];
        }
        mean = total / sortedData.length;
        meanTxt.setText(Double.toString(mean));
    }

    public void calcMedian() {
        int middle = sortedData.length / 2;
        int rightOfMedian = (sortedData.length + 1) / 2;
        int leftOfMedian = (sortedData.length - 1) / 2;
        double leftD = sortedData[leftOfMedian + 1];
        double rightD = sortedData[leftOfMedian];
        double median = (leftD + rightD) / 2.0;
        if (sortedData.length % 2 == 1) {
            medianTxt.setText(Double.toString(sortedData[middle]));
            calcQ1true(middle);
            calcQ3true(middle);
        } else {
            medianTxt.setText(Double.toString(median));
            calcQ1false(leftOfMedian);
            calcQ3false(rightOfMedian);
        }
    }

    public void calcQ1true(int Median) {
        int middle = Median / 2;
        int m1 = Median - 1;
        int m2 = Median + 1;
        int Q1L = m1 / 2;
        int Q1R = m2 / 2;
        double median = (sortedData[Q1L] + sortedData[Q1R]) / 2;
        if (Median % 2 == 0) {
            Q1Txt.setText(Double.toString(sortedData[middle]));
        } else {
            Q1Txt.setText(Double.toString(median));
        }
    }

    public void calcQ1false(int leftBound) {
        int middle = leftBound / 2;
        int m1 = leftBound - 1;
        int m2 = leftBound + 1;
        int Q1L = m1 / 2;
        int Q1R = m2 / 2;
        double median = (sortedData[Q1L] + sortedData[Q1R]) / 2;
        if (leftBound % 2 == 0) {
            Q1Txt.setText(Double.toString(sortedData[middle]));
        } else {
            Q1Txt.setText(Double.toString(median));
        }
    }

    public void calcQ3true(int Median) {
        int upper = Median + sortedData.length;
        int middle = (upper) / 2;
        int lOM = (upper - 1) / 2;
        double leftD = sortedData[lOM + 1];
        double rightD = sortedData[lOM];
        double median = (leftD + rightD) / 2.0;
        if (upper % 2 == 1) {
            Q3Txt.setText(Double.toString(sortedData[middle]));
        } else {
            Q3Txt.setText(Double.toString(median));
        }
    }

    public void calcQ3false(int rightBound) {
        int upper = rightBound + sortedData.length;
        int middle = (upper) / 2;
        int lOM = (upper - 1) / 2;
        double leftD = sortedData[lOM + 1];
        double rightD = sortedData[lOM];
        double median = (leftD + rightD) / 2.0;
        if (upper % 2 == 1) {
            Q3Txt.setText(Double.toString(sortedData[middle]));
        } else {
            Q3Txt.setText(Double.toString(median));
        }
    }

    public void calcRange() {
        double max = sortedData[sortedData.length - 1];
        double min = sortedData[0];
        double range = max - min;
        rangeTxt.setText("Ranges from: " + min + " to " + max + " (" + range + ")");
    }

    public void calcIQR() {
        double Q1 = Double.parseDouble(Q1Txt.getText());
        double Q3 = Double.parseDouble(Q3Txt.getText());
        double IQR = Q3 - Q1;
        IQRTxt.setText(Double.toString(IQR));

    }

    public void calcStdDev() {
        double stdDev;
        double sum = 0;
        for (int i = 0; i < sortedData.length; i++) {
            sum += Math.pow(sortedData[i] - mean, 2);
        }
        stdDev = Math.sqrt(sum / (sortedData.length - 1));
        stdDevTxt.setText(Double.toString(stdDev));
    }

    public void calcFiveNumSum() {
        double min = sortedData[0];
        double Q1 = Double.parseDouble(Q1Txt.getText());
        double Q2 = Double.parseDouble(medianTxt.getText());
        double Q3 = Double.parseDouble(Q3Txt.getText());
        double max = sortedData[sortedData.length - 1];
        double fiveNumSum = min + Q1 + Q2 + Q3 + max;
        fiveNumSumTxt.setText(min + " + " + Q1 + " + " + Q2 + " + " + Q3 + " + " + max + " = " + fiveNumSum);
    }

    public void calcLowOut() {
        double Q1 = Double.parseDouble(Q1Txt.getText());
        double IQR = Double.parseDouble(IQRTxt.getText());
        double lowOut = Q1 - 1.5 * IQR;
        lowOutTxt.setText(Double.toString(lowOut));
    }

    public void calcUpOut() {
        double Q3 = Double.parseDouble(Q3Txt.getText());
        double IQR = Double.parseDouble(IQRTxt.getText());
        double upOut = Q3 + 1.5 * IQR;
        upOutTxt.setText(Double.toString(upOut));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statsCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statsCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statsCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statsCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statsCalcGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IQRTxt;
    private javax.swing.JLabel IRQLbl;
    private javax.swing.JLabel Q1Lbl;
    private javax.swing.JTextField Q1Txt;
    private javax.swing.JLabel Q3Lbl;
    private javax.swing.JTextField Q3Txt;
    private javax.swing.JButton calculate;
    private javax.swing.JTextArea displayDataTxt;
    private javax.swing.JLabel enterDataLbl;
    private javax.swing.JTextField enterDataTxt;
    private javax.swing.JLabel fiuveNumSumLbl;
    private javax.swing.JTextField fiveNumSumTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lowOutLbl;
    private javax.swing.JTextField lowOutTxt;
    private javax.swing.JLabel meanLbl;
    private javax.swing.JTextField meanTxt;
    private javax.swing.JLabel medianLbl;
    private javax.swing.JTextField medianTxt;
    private javax.swing.JLabel rangeLbl;
    private javax.swing.JTextField rangeTxt;
    private javax.swing.JButton resetBut;
    public static javax.swing.JTextArea sortedTxt;
    private javax.swing.JLabel stdDevLbl;
    private javax.swing.JTextField stdDevTxt;
    private javax.swing.JLabel upOutLbl;
    private javax.swing.JTextField upOutTxt;
    // End of variables declaration//GEN-END:variables
    public static ArrayList<Double> data = new ArrayList<>();
    public static double[] sortedData = new double[data.size()];
    private double total;
    private double sumSqrd;
    public double mean;
}
